"""Update

Revision ID: bb9024168011
Revises: 8449debee63f
Create Date: 2024-11-06 21:47:29.938086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9024168011'
down_revision = '8449debee63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.drop_column('option_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_text', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
